Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/09/2019
Var
// Seção de Declarações das variáveis 
a:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
a:=11
repita
a:=a-1
escreva(a,",")
ate(a<=1)
Fimalgoritmo