Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/09/2019
Var
// Seção de Declarações das variáveis 
a:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
a:=0
enquanto (a<100) faca
a:=a
a:=a+1
escreval(a)
fimenquanto
Fimalgoritmo