Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/09/2019
Var
// Seção de Declarações das variáveis 
a:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
enquanto a<2 faca
a:=a+0.01
escreva(a)
fimenquanto
Fimalgoritmo