Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/09/2019
Var
// Seção de Declarações das variáveis
a:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para a de 0 ate 20 passo 2 faca
escreva(a,"-")
fimpara
Fimalgoritmo