Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/09/2019
Var
// Seção de Declarações das variáveis 
a,b,c,d:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
a:=1
b:=0
para d de 1 ate 15 faca
c:=a+b
escreva(c,"-")
a:=b
b:=c
fimpara
Fimalgoritmo