Algoritmo "Soma números de 100 até 200"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/09/2019
Var
// Seção de Declarações das variáveis 
a,b:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
a:=100
para a de 100 ate 200 passo 1 faca
b:=b+a
fimpara
escreval("A soma resultara:",b)
Fimalgoritmo