Algoritmo "Atividade 5"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/10/2019
Var
// Seção de Declarações das variáveis 
a:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

repita
escreval("Informe um novo valor:")
leia(a)
ate (a>0)e(a<100)
escreval("Número válido")
Fimalgoritmo