Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/09/2019
Var
// Seção de Declarações das variáveis 
a,b:inteiro
c:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
b:=1
para a de 1 ate 99 passo 2 faca
c:=c+(a/b)
b:=b+1
fimpara
escreval(c)

Fimalgoritmo