Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/07/2019
Var
// Seção de Declarações das variáveis 
a: real
r: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Insisira o valor do raio")
leia(r)
a:=3.14*r*r
escreval
escreval("A área calculada é:",a)
Fimalgoritmo